# Random Over Sampling

### 1. Upload Data

In [1]:
import pandas as pd
df = pd.read_excel('data.xlsx')
df

x1  x2  y
0   2   2  1
1   3   3  1
2   2   5  1
3   1   1  0
4   5   8  0
5   3   5  0
6   2   4  0
7   3   6  0
8   4   2  0

Ubah data frame kedalam bentuk sparse matrik

In [2]:
data = df.as_matrix(columns=df.columns[0:])
data

array([[2, 2, 1],
       [3, 3, 1],
       [2, 5, 1],
       [1, 1, 0],
       [5, 8, 0],
       [3, 5, 0],
       [2, 4, 0],
       [3, 6, 0],
       [4, 2, 0]])

### 2. Preprocessing Data

Pisahkan atribut dan target value dari matrik diatas. Asumsi atribut X dan target value atau class Y.

In [3]:
X = data[:,[0,1]]
X

array([[2, 2],
       [3, 3],
       [2, 5],
       [1, 1],
       [5, 8],
       [3, 5],
       [2, 4],
       [3, 6],
       [4, 2]])

In [4]:
Y = data [:,2]
Y

array([1, 1, 1, 0, 0, 0, 0, 0, 0])

Import RAndomOVerSampler , Jika belum di install install menggunkan " pip install imblearn "

In [5]:
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler()
X_resampled, Y_resampled = ros.fit_sample(X, Y)

In [6]:
X_resampled

array([[2, 2],
       [3, 3],
       [2, 5],
       [1, 1],
       [5, 8],
       [3, 5],
       [2, 4],
       [3, 6],
       [4, 2],
       [3, 3],
       [2, 5],
       [3, 3]])

In [7]:
Y_resampled

array([1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1])

In [8]:
import numpy as np
y = Y_resampled.reshape(-1,1)
y

array([[1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1]])

In [9]:
data_resampled = np.concatenate((X_resampled,y),axis=1)
data_resampled

array([[2, 2, 1],
       [3, 3, 1],
       [2, 5, 1],
       [1, 1, 0],
       [5, 8, 0],
       [3, 5, 0],
       [2, 4, 0],
       [3, 6, 0],
       [4, 2, 0],
       [3, 3, 1],
       [2, 5, 1],
       [3, 3, 1]])

### 3. Uji Coba

Uji coba dilakukan dengan metode klasifikasi naive bayes, dimana pada python terdapat 3 jenis. Penggolongan ini dilakukan berdasarkan jenis data yang dipergunakan. Adaputn ketiga jenis naive bayes yang dipergunakan adalah:
a) Gaussian: It assumes that continuous features follow a normal distribution.
b) Multinomial: It is useful if your features are discrete.
c) Bernoulli: The binomial model is useful if your features are binary.

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_resampled, Y_resampled, test_size=0.33, random_state=42)

In [16]:
from sklearn.naive_bayes import GaussianNB, BernoulliNB, MultinomialNB
gnb = GaussianNB()
y_pred = gnb.fit(X_train, y_train).predict(X_test)

In [12]:
y_pred

array([0, 1, 0, 0])

In [14]:
y_test

array([1, 1, 1, 0])

#### TIngkat uji precision & recall

In [15]:
from sklearn.metrics import classification_report
target_names = ['class 0', 'class 1']
print(classification_report(y_test, y_pred, target_names=target_names))

             precision    recall  f1-score   support

    class 0       0.33      1.00      0.50         1
    class 1       1.00      0.33      0.50         3

avg / total       0.83      0.50      0.50         4



#### Tingkat uji akurasi

In [17]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.5
